In [79]:
%matplotlib notebook
%matplotlib inline

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import scipy.stats as stats
import numpy as np

In [80]:
# data files
AU_Region_Mobility_Report = "data/2020_AU_Region_Mobility_Report.csv"

# Read the mouse data and the study results
AU_Region_Mobility = pd.read_csv(AU_Region_Mobility_Report)

In [81]:
AU_Region_Mobility.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AU,Australia,NaN,NaN,NaN,NaN,NaN,ChIJ38WHZwf9KysRUhNblaFnglM,2020-02-15,4.0,3.0,-2.0,3.0,3.0,0.0
1,AU,Australia,NaN,NaN,NaN,NaN,NaN,ChIJ38WHZwf9KysRUhNblaFnglM,2020-02-16,3.0,5.0,9.0,3.0,-1.0,0.0
2,AU,Australia,NaN,NaN,NaN,NaN,NaN,ChIJ38WHZwf9KysRUhNblaFnglM,2020-02-17,-1.0,0.0,-6.0,7.0,17.0,-2.0
3,AU,Australia,NaN,NaN,NaN,NaN,NaN,ChIJ38WHZwf9KysRUhNblaFnglM,2020-02-18,-3.0,-2.0,-13.0,7.0,14.0,-1.0
4,AU,Australia,NaN,NaN,NaN,NaN,NaN,ChIJ38WHZwf9KysRUhNblaFnglM,2020-02-19,-1.0,-1.0,-6.0,8.0,13.0,-1.0

There are many NAN values. we need to clean? or leave as empty for sorting later on?

In [85]:
# Convert NaN values to empty String
nan_value =float("NaN")
AU_Region_Mobility.replace("",nan_value, inplace= True)
#only dropping NaN in sub_region_1 because if there is no state then there is no usable references
AU_Region_Mobility_cleaned = AU_Region_Mobility.dropna(subset=['sub_region_1'],inplace= True)
AU_Region_Mobility = pd.DataFrame(AU_Region_Mobility)
AU_Region_Mobility.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
393,AU,Australia,Australian Capital Territory,NaN,NaN,AU-ACT,NaN,ChIJSxCboN9MFmsRA3huXDhEWOc,2020-02-15,7.0,5.0,28.0,4.0,6.0,-1.0
394,AU,Australia,Australian Capital Territory,NaN,NaN,AU-ACT,NaN,ChIJSxCboN9MFmsRA3huXDhEWOc,2020-02-16,8.0,19.0,34.0,16.0,2.0,-2.0
395,AU,Australia,Australian Capital Territory,NaN,NaN,AU-ACT,NaN,ChIJSxCboN9MFmsRA3huXDhEWOc,2020-02-17,-1.0,10.0,9.0,21.0,25.0,-4.0
396,AU,Australia,Australian Capital Territory,NaN,NaN,AU-ACT,NaN,ChIJSxCboN9MFmsRA3huXDhEWOc,2020-02-18,-2.0,-1.0,-11.0,12.0,24.0,-2.0
397,AU,Australia,Australian Capital Territory,NaN,NaN,AU-ACT,NaN,ChIJSxCboN9MFmsRA3huXDhEWOc,2020-02-19,2.0,9.0,12.0,17.0,22.0,-3.0

In [91]:
# group by states use for all summaries
summary_statistics_df = AU_Region_Mobility.groupby('sub_region_1')

# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the movement types for each state
summary_retail_and_recreation = summary_statistics_df.agg(['mean','median','var','std','sem'])["retail_and_recreation_percent_change_from_baseline"]
#flatten the index
summary_retail_and_recreation.columns = [''.join(col).strip() for col in summary_retail_and_recreation.columns.values]

# convert to dataframe
summary_retail_and_recreation = pd.DataFrame(summary_retail_and_recreation)

# This gives us the summary on changes for retail_and_recreation_percent_change_from_baseline in 2020
#The standard deviation (sd) describes the variability between individuals in a sample; 
# The standard error of the mean (sem) describes the uncertainty of how the sample mean represents the population mean
# SEM is how far your estimate of the mean is likely to be from the true population mean.The lower the more accurate.
summary_retail_and_recreation

,mean,median,var,std,sem
sub_region_1,,,,,
Australian Capital Territory,-12.374046,-10.0,206.551059,14.371884,0.724966
New South Wales,-10.860346,-8.0,329.606672,18.155073,0.113663
Northern Territory,6.444068,9.0,265.983810,16.309010,0.424650
Queensland,-3.989606,-2.0,276.029622,16.614139,0.169382
South Australia,-8.888346,-5.0,329.010754,18.138654,0.191188
Tasmania,-16.282409,-13.0,256.137404,16.004293,0.284929
Victoria,-24.182093,-21.0,454.582656,21.320944,0.150121
Western Australia,-4.879457,-1.0,394.052654,19.850760,0.176894

In [84]:
#,["grocery_and_pharmacy_percent_change_from_baseline"],["parks_percent_change_from_baseline"],["transit_stations_percent_change_from_baseline"],
#["workplaces_percent_change_from_baseline"],["residential_percent_change_from_baseline"]